version: "3.8"

services:
  db:
    image: postgres:15
    container_name: hamburgueria_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: avengeda7x!
      POSTGRES_DB: hamburgueriadb
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: hamburgueria_backend
    ports:
      - "3333:3333"
    depends_on:
      - db
    env_file:
    - ./backend/.env

  frontend:
    build: ./frontend
    container_name: hamburgueria_frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    env_file:
      - ./frontend/.env

volumes:
  postgres_data: