version: "3.8"

services:
  db:
    image: postgres:15
    container_name: hamburgueria_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: avengeda7x!
      POSTGRES_DB: hamburgueriadb
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: hamburgueria_backend
    ports:
      - "3334:3333"
    depends_on:
      - db
    env_file:
    - ./backend/.env
    environment:
      PORT: 3333

  frontend:
    build: ./frontend
    container_name: hamburgueria_frontend
    ports:
      - "3001:3000"
    depends_on:
      - backend
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:3333
      API_URL: http://backend:3333

volumes:
  postgres_data: